version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: docker/dockerfile
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    ports:
      - "9000:9000"

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf.d:/etc/nginx/conf.d
      - ./public:/app/public
